-- Crear tablas para tipos y turnos
create table if not exists public.tipos (
  id bigint generated by default as identity primary key,
  nombre text not null,
  precio numeric not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.turnos (
  id bigint generated by default as identity primary key,
  nombre text not null,
  telefono text not null,
  tipo_id bigint references public.tipos(id),
  fecha date not null,
  hora text not null,
  notas text,
  estado text not null default 'pendiente',
  created_at timestamptz not null default now()
);

create index if not exists turnos_fecha_idx on public.turnos (fecha);
create index if not exists turnos_estado_idx on public.turnos (estado);

alter table public.tipos enable row level security;
alter table public.turnos enable row level security;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'tipos' AND policyname = 'tipos_read'
  ) THEN
    CREATE POLICY "tipos_read" ON public.tipos FOR SELECT USING (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'tipos' AND policyname = 'tipos_insert'
  ) THEN
    CREATE POLICY "tipos_insert" ON public.tipos FOR INSERT WITH CHECK (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'tipos' AND policyname = 'tipos_update'
  ) THEN
    CREATE POLICY "tipos_update" ON public.tipos FOR UPDATE USING (true) WITH CHECK (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'turnos' AND policyname = 'turnos_read'
  ) THEN
    CREATE POLICY "turnos_read" ON public.turnos FOR SELECT USING (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'turnos' AND policyname = 'turnos_insert'
  ) THEN
    CREATE POLICY "turnos_insert" ON public.turnos FOR INSERT WITH CHECK (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'turnos' AND policyname = 'turnos_update'
  ) THEN
    CREATE POLICY "turnos_update" ON public.turnos FOR UPDATE USING (true) WITH CHECK (true);
  END IF;
END $$;
