-- Crear tablas para tipos y turnos
create table if not exists public.tipos (
  id bigint generated by default as identity primary key,
  nombre text not null,
  precio numeric not null default 0,
  descripcion text not null default '',
  duracion text not null default '',
  imagen_url text,
  imagen_path text,
  created_at timestamptz not null default now()
);

alter table public.tipos
  add column if not exists descripcion text not null default '',
  add column if not exists duracion text not null default '',
  add column if not exists imagen_url text,
  add column if not exists imagen_path text;

create table if not exists public.turnos (
  id bigint generated by default as identity primary key,
  nombre text not null,
  email text,
  telefono text not null,
  tipo_id bigint references public.tipos(id),
  fecha date not null,
  hora text not null,
  notas text,
  estado text not null default 'pendiente',
  forma_pago text,
  precio_pagado numeric,
  created_at timestamptz not null default now()
);

create table if not exists public.clientes (
  id bigint generated by default as identity primary key,
  nombre text not null check (btrim(nombre) <> ''),
  telefono text,
  preferencias text,
  observaciones text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.turnos
  add column if not exists email text,
  add column if not exists forma_pago text,
  add column if not exists precio_pagado numeric;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'public.turnos'::regclass AND conname = 'turnos_forma_pago_check'
  ) THEN
    ALTER TABLE public.turnos
      ADD CONSTRAINT turnos_forma_pago_check
      CHECK (forma_pago IS NULL OR forma_pago IN ('efectivo', 'transferencia', 'cuenta_bancaria'));
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'public.turnos'::regclass AND conname = 'turnos_precio_pagado_check'
  ) THEN
    ALTER TABLE public.turnos
      ADD CONSTRAINT turnos_precio_pagado_check
      CHECK (precio_pagado IS NULL OR precio_pagado >= 0);
  END IF;
END $$;

create index if not exists turnos_fecha_idx on public.turnos (fecha);
create index if not exists turnos_estado_idx on public.turnos (estado);

alter table public.tipos enable row level security;
alter table public.turnos enable row level security;
alter table public.clientes enable row level security;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.clientes TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.clientes_id_seq TO authenticated;
GRANT DELETE ON public.turnos TO authenticated;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'tipos' AND policyname = 'tipos_read'
  ) THEN
    CREATE POLICY "tipos_read" ON public.tipos FOR SELECT USING (true);
  END IF;

  DROP POLICY IF EXISTS "tipos_insert_admin" ON public.tipos;
  CREATE POLICY "tipos_insert_admin" ON public.tipos FOR INSERT WITH CHECK (
    auth.uid() IS NOT NULL AND (
      lower(coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '')) = 'admin' OR
      lower(coalesce(auth.email(), '')) = 'admin@aura-nails.local'
    )
  );

  DROP POLICY IF EXISTS "tipos_update_admin" ON public.tipos;
  CREATE POLICY "tipos_update_admin" ON public.tipos FOR UPDATE USING (
    auth.uid() IS NOT NULL AND (
      lower(coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '')) = 'admin' OR
      lower(coalesce(auth.email(), '')) = 'admin@aura-nails.local'
    )
  ) WITH CHECK (
    auth.uid() IS NOT NULL AND (
      lower(coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '')) = 'admin' OR
      lower(coalesce(auth.email(), '')) = 'admin@aura-nails.local'
    )
  );

  INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
  VALUES ('servicios', 'servicios', true, 5242880, ARRAY['image/jpeg', 'image/png', 'image/webp'])
  ON CONFLICT (id) DO UPDATE
    SET public = EXCLUDED.public,
        file_size_limit = EXCLUDED.file_size_limit,
        allowed_mime_types = EXCLUDED.allowed_mime_types;

  DROP POLICY IF EXISTS "servicios_public_read" ON storage.objects;
  CREATE POLICY "servicios_public_read" ON storage.objects FOR SELECT
    USING (bucket_id = 'servicios');

  DROP POLICY IF EXISTS "servicios_admin_insert" ON storage.objects;
  CREATE POLICY "servicios_admin_insert" ON storage.objects FOR INSERT
    WITH CHECK (
      bucket_id = 'servicios' AND auth.uid() IS NOT NULL AND (
        lower(coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '')) = 'admin' OR
        lower(coalesce(auth.email(), '')) = 'admin@aura-nails.local'
      )
    );

  DROP POLICY IF EXISTS "servicios_admin_delete" ON storage.objects;
  CREATE POLICY "servicios_admin_delete" ON storage.objects FOR DELETE
    USING (
      bucket_id = 'servicios' AND auth.uid() IS NOT NULL AND (
        lower(coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '')) = 'admin' OR
        lower(coalesce(auth.email(), '')) = 'admin@aura-nails.local'
      )
    );

  DROP POLICY IF EXISTS "turnos_read" ON public.turnos;
  CREATE POLICY "turnos_read" ON public.turnos FOR SELECT USING (
    auth.uid() IS NOT NULL AND (
      lower(coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '')) = 'admin' OR
      lower(coalesce(auth.email(), '')) = 'admin@aura-nails.local'
    )
  );

  DROP POLICY IF EXISTS "turnos_insert_public" ON public.turnos;
  CREATE POLICY "turnos_insert_public" ON public.turnos FOR INSERT WITH CHECK (
    nombre IS NOT NULL AND btrim(nombre) <> '' AND
    email IS NOT NULL AND btrim(email) <> '' AND
    telefono IS NOT NULL AND btrim(telefono) <> '' AND
    fecha IS NOT NULL AND hora IS NOT NULL AND hora <> ''
  );

  DROP POLICY IF EXISTS "turnos_update_admin" ON public.turnos;
  CREATE POLICY "turnos_update_admin" ON public.turnos FOR UPDATE USING (
    auth.uid() IS NOT NULL AND (
      lower(coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '')) = 'admin' OR
      lower(coalesce(auth.email(), '')) = 'admin@aura-nails.local'
    )
  ) WITH CHECK (
    auth.uid() IS NOT NULL AND (
      lower(coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '')) = 'admin' OR
      lower(coalesce(auth.email(), '')) = 'admin@aura-nails.local'
    )
  );

  DROP POLICY IF EXISTS "turnos_delete_admin" ON public.turnos;
  CREATE POLICY "turnos_delete_admin" ON public.turnos FOR DELETE USING (
    auth.uid() IS NOT NULL AND (
      lower(coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '')) = 'admin' OR
      lower(coalesce(auth.email(), '')) = 'admin@aura-nails.local'
    )
  );

  DROP POLICY IF EXISTS "clientes_select_admin" ON public.clientes;
  CREATE POLICY "clientes_select_admin" ON public.clientes FOR SELECT USING (
    auth.uid() IS NOT NULL AND (
      lower(coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '')) = 'admin' OR
      lower(coalesce(auth.email(), '')) = 'admin@aura-nails.local'
    )
  );

  DROP POLICY IF EXISTS "clientes_insert_admin" ON public.clientes;
  CREATE POLICY "clientes_insert_admin" ON public.clientes FOR INSERT WITH CHECK (
    auth.uid() IS NOT NULL AND (
      lower(coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '')) = 'admin' OR
      lower(coalesce(auth.email(), '')) = 'admin@aura-nails.local'
    )
  );

  DROP POLICY IF EXISTS "clientes_update_admin" ON public.clientes;
  CREATE POLICY "clientes_update_admin" ON public.clientes FOR UPDATE USING (
    auth.uid() IS NOT NULL AND (
      lower(coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '')) = 'admin' OR
      lower(coalesce(auth.email(), '')) = 'admin@aura-nails.local'
    )
  ) WITH CHECK (
    auth.uid() IS NOT NULL AND (
      lower(coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '')) = 'admin' OR
      lower(coalesce(auth.email(), '')) = 'admin@aura-nails.local'
    )
  );

  DROP POLICY IF EXISTS "clientes_delete_admin" ON public.clientes;
  CREATE POLICY "clientes_delete_admin" ON public.clientes FOR DELETE USING (
    auth.uid() IS NOT NULL AND (
      lower(coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '')) = 'admin' OR
      lower(coalesce(auth.email(), '')) = 'admin@aura-nails.local'
    )
  );
END $$;

CREATE OR REPLACE FUNCTION public.get_booked_hours(p_fecha date)
RETURNS TABLE (hora text)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT turnos.hora
  FROM public.turnos
  WHERE turnos.fecha = p_fecha
    AND turnos.estado <> 'cancelado';
$$;

REVOKE ALL ON FUNCTION public.get_booked_hours(date) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_booked_hours(date) TO anon, authenticated;

NOTIFY pgrst, 'reload schema';
