-- Crear tablas para tipos y turnos
create table if not exists public.tipos (
  id bigint generated by default as identity primary key,
  nombre text not null,
  precio numeric not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.turnos (
  id bigint generated by default as identity primary key,
  nombre text not null,
  telefono text not null,
  tipo_id bigint references public.tipos(id),
  fecha date not null,
  hora text not null,
  notas text,
  estado text not null default 'pendiente',
  created_at timestamptz not null default now()
);

create index if not exists turnos_fecha_idx on public.turnos (fecha);
create index if not exists turnos_estado_idx on public.turnos (estado);

alter table public.tipos enable row level security;
alter table public.turnos enable row level security;

create policy if not exists "tipos_read" on public.tipos for select using (true);
create policy if not exists "tipos_insert" on public.tipos for insert with check (true);
create policy if not exists "tipos_update" on public.tipos for update using (true) with check (true);

create policy if not exists "turnos_read" on public.turnos for select using (true);
create policy if not exists "turnos_insert" on public.turnos for insert with check (true);
create policy if not exists "turnos_update" on public.turnos for update using (true) with check (true);
